name: pism-terra
channels:
  - conda-forge
  - pism
dependencies:
  - python
  - pip
  # runtime requirements
  - awscrt  # boto3 extra needed
  - boto3
  - botocore
  - python-cdo
  - cf_xarray
  - cfgrib
  - cftime
  - cmap
  - cmweather
  - dask[distributed,dataframe]
  - dem_stitcher
  - earthaccess
  - ecmwf-datastores-client
  - geocube
  - geopandas
  - jinja2
  - joblib
  - libgdal-core
  - libgdal-hdf5
  - libgdal-netcdf
  - matplotlib
  - mpi4py
  - nc-time-axis
  - libnetcdf=*=*openmpi*
  - netcdf4=*=*openmpi*
  - h5py=*=*openmpi*
  - hdf5=*=*openmpi*
  - netCDF4
  - numpy
  - openmpi >=5
  - pandas
  - pint-xarray
  - pyamg
  - pyarrow
  - pydantic
  - pyfiglet
  - pyogrio
  - pyproj
  - pytest
  - rasterio
  - requests
  - rioxarray
  - s3fs
  - scikit-learn
  - scipy
  - shapely
  - toml
  - tqdm
  - xarray
  - xarray-regrid
  - yac=*=*openmpi*
  - yaxt=*=*openmpi*
  - zarr
  # for development and testing
  - black
  - pre-commit
  - pylint
  - pytest
  - pytest-codeblocks
  - pytest-cov
  - setuptools_scm>=6.2
  # for docs
  - furo
  - ipykernel
  - myst-nb
  - numpydoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-book-theme
  - sphinx-design
  - sphinx-gallery
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinxcontrib-bibtex
  - myst-parser
  - numpydoc
  # for notebooks and convenience
  - cdo
  - ncview
  - cmcrameri
  - bokeh
  - cartopy
  - flox  # FIXME: possibly a runtime requirement for xarray/dask performance
  - hyp3_sdk
  - jupyter
  - jupyter-server-proxy
  - moviepy
  - python-dateutil
  - seaborn
