name: pism-terra
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  # runtime requirements
  - awscrt  # boto3 extra needed
  - boto3
  - botocore
  - cdsapi
  - python-cdo
  # - cf_units  # FIXME: Breaks this environment; doesn't appear to be needed
  - cf_xarray
  - cftime
  - dask[distributed,dataframe]
  - dem_stitcher
  - earthaccess
  - geocube
  - geopandas
  - h5netcdf
  - jinja2
  - joblib
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pint-xarray
  - pyamg
  - pyarrow
  - pydantic
  - pyfiglet
  - pyogrio
  - pyproj
  - pytest
  - rasterio
  - requests
  - rioxarray
  - s3fs
  - scikit-learn
  - scipy
  - shapely
  - toml
  - tqdm
  - xarray
  - xarray-regrid
  - zarr
  # for development and testing
  - black
  - pre-commit
  - pylint
  - pytest
  - pytest-cov
  - setuptools_scm>=6.2
  # for docs
  - furo
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - myst-parser
  - numpydoc
  # for notebooks and convenience
  - cdo
  - ncview
  - cmcrameri
  - bokeh
  - cartopy
  - flox  # FIXME: possibly a runtime requirement for xarray/dask performance
  - hyp3_sdk
  - jupyter
  - jupyter-server-proxy
  - moviepy
  - python-dateutil
  - seaborn
