samples = 25
mapping = {"atmosphere.given.file"= "climate_file", "surface.given.file"= "climate_file"}

['surface.debm_simple.c1']

loc = 25
scale = 10
distribution = "uniform"

['surface.debm_simple.c2']

loc = -130
scale = 10
distribution = "uniform"

['debm_simple.air_temp_all_precip_as_snow']

loc = 272.15
scale = 1
distribution = "uniform"
