samples = 50
mapping = {"atmosphere.given.file"= "climate_file", "surface.given.file"= "climate_file"}

['surface.debm_simple.c1']

loc = 0
scale = 40
distribution = "uniform"

['surface.debm_simple.c2']

loc = -150
scale = 150
distribution = "uniform"
