samples = 3

['ocean.plume.power_alpha']

choices = [0.33333333]
distribution = "choices"

['ocean.plume.power_beta']

choices = [2.0]
distribution = "choices"

['ocean.plume.drag_coefficient']

choices = [1.2e-3]
distribution = "choices"

['ocean.plume.length_scale_factor']

choices = [0.15, 0.20, 0.25]
distribution = "choices"
