samples = 48

['ocean.plume.power_alpha']

choices = [0.33333333, 0.54]
distribution = "choices"

['ocean.plume.power_beta']

choices = [2.0]
distribution = "choices"

['ocean.plume.drag_coefficient']

choices = [1.5e-3, 2.5e-3]
distribution = "choices"

['ocean.plume.length_scale_factor']

choices = [0.15, 0.25, 0.35]
distribution = "choices"

['ocean.plume.melt_rate_parameter']

choices = [1, 2, 5, 10]
distribution = "choices"
