samples = 150

['surface.pdd.factor_ice']

loc = 0.006
scale = 0.0010
distribution = "uniform"

['surface.pdd.factor_snow']

loc = 0.002
scale = 0.004
distribution = "uniform"

['surface.pdd.air_temp_all_precip_as_snow']

loc = 271.15
scale = 1
distribution = "uniform"

['surface.pdd.air_temp_all_precip_as_rain']

loc = 273.15
scale = 4
distribution = "uniform"

['surface.pdd.refreeze']

loc = 0.2
scale = 0.6
distribution = "uniform"
