# Copyright (C) 2026 Andy Aschwanden
#
# This file is part of pism-terra.
#
# PISM-TERRA is free software; you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation; either version 3 of the License, or (at your option) any later
# version.
#
# PISM-TERRA is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License
# along with PISM; if not, write to the Free Software

"""
Reduce a penalty sweep to the small fixture the L-curve example reads.

Each ``inv_*.nc`` from a Tikhonov sweep is ~2 GB, almost all of it 3-D fields
the L-curve does not need. This keeps the per-iteration diagnostics (a few
hundred floats per member) and collapses the one 2-D field that matters ---
the velocity residual --- into a single weighted RMS per member, so the whole
sweep fits in tens of kilobytes and can live in the repository.

Run it when the sweep is regenerated::

    python docs/make_data/lcurve_fixture.py 2026_08_ismip7_inv_penalty/output/inverse \\
        docs/source/_data/gris_lcurve_penalty.nc
"""

import sys
from pathlib import Path

import numpy as np
import xarray as xr

# Per-iteration diagnostics worth keeping: the two objective terms and the
# gradient norms the stopping test compares.
TRACES = ["inv_J_misfit", "J_design", "grad_sum", "grad_state", "grad_design"]


def weighted_rms(ds: xr.Dataset) -> float:
    """
    Collapse the velocity residual into one misfit number.

    Parameters
    ----------
    ds : xarray.Dataset
        An inversion output carrying ``inv_residual`` and
        ``vel_misfit_weight``.

    Returns
    -------
    float
        Area-weighted RMS of ``|u_model - u_obs|`` over the misfit domain, in
        m/yr. This is the physical counterpart of the dimensionless
        ``inv_J_misfit``.
    """
    weight = ds["vel_misfit_weight"].squeeze().values.astype(float)
    residual = ds["inv_residual"].squeeze().values.astype(float)
    return float(np.sqrt(np.nansum(weight * residual**2) / np.nansum(weight)))


def build(inv_dir: Path, pattern: str = "inv_*.nc") -> xr.Dataset:
    """
    Read every member of a sweep and stack the reduced diagnostics.

    Members are returned sorted by penalty weight, which is the order an
    L-curve is drawn in.

    Parameters
    ----------
    inv_dir : pathlib.Path
        Directory holding one ``inv_*.nc`` per ensemble member.
    pattern : str, default "inv_*.nc"
        Glob selecting the members.

    Returns
    -------
    xarray.Dataset
        Dimensions ``member`` and ``inv_iter``; the traces plus scalar
        ``penalty_weight`` and ``misfit_rms`` per member.

    Raises
    ------
    FileNotFoundError
        If the pattern matches nothing.
    """
    files = sorted(inv_dir.glob(pattern))
    if not files:
        raise FileNotFoundError(f"no files matching {pattern!r} in {inv_dir}")

    members = []
    for path in files:
        with xr.open_dataset(path, decode_times=False) as ds:
            member = ds[TRACES].reset_coords(drop=True)
            member["penalty_weight"] = float(ds.pism_config.attrs["inverse.tikhonov.penalty_weight"])
            member["misfit_rms"] = weighted_rms(ds)
            members.append(member.compute())
        print(
            f"  {path.name}: penalty={float(members[-1]['penalty_weight']):g} "
            f"misfit={float(members[-1]['misfit_rms']):.2f} m/yr"
        )

    out = xr.concat(members, dim="member").sortby("penalty_weight")
    out["penalty_weight"].attrs = {"long_name": "Tikhonov penalty weight eta", "units": "1"}
    out["misfit_rms"].attrs = {
        "long_name": "area-weighted RMS velocity misfit over the misfit domain",
        "units": "m year^-1",
    }
    out.attrs = {
        "title": "Tikhonov penalty sweep reduced for the L-curve example",
        "source": str(inv_dir),
        "note": "Generated by docs/make_data/lcurve_fixture.py; see docs/source/greenland/inversion.md",
    }
    return out


def main() -> int:
    """
    Write the fixture named on the command line.

    Returns
    -------
    int
        Exit code (0 for success).
    """
    if len(sys.argv) != 3:
        print(__doc__)
        return 2

    inv_dir, outfile = Path(sys.argv[1]), Path(sys.argv[2])
    print(f"Reading {inv_dir}")
    out = build(inv_dir)

    outfile.parent.mkdir(parents=True, exist_ok=True)
    outfile.unlink(missing_ok=True)
    # The source files declare an unlimited ``time``; the fixture has no such
    # dimension, and carrying the stale encoding over warns on write.
    out.encoding.pop("unlimited_dims", None)
    encoding = {name: {"zlib": True, "complevel": 4} for name in out.data_vars}
    out.to_netcdf(outfile, encoding=encoding)
    print(
        f"\nWrote {outfile} ({outfile.stat().st_size / 1024:.0f} KB) "
        f"for {out.sizes['member']} members x {out.sizes['inv_iter']} iterations"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
