ismip7_to_pism = {"acabf" = "climatic_mass_balance", "runoff" = "water_input_rate", "tas" = "ice_surface_temp", "TF" = "theta_ocean", "geothermal_heat_flux1" = "bheatflx"}
version = "v2"
bucket = "pism-cloud-data"
prefix = "ismip7/greenland/input"

[domain]

x_bounds = [-653000.0, 879700.0]
y_bounds = [-3384350.0, -632750.0]
resolution = "900m"

[gcms]

'CESM2-WACCM' = {ssp126 = {"historical" = [1978, 2015], "projection" = [2015, 2299], version = 2 }, ssp370 = {"historical" = [1978, 2015], "projection" = [2015, 2299], version = 2 }, ssp585 = {"historical" = [1978, 2015], "projection" = [2015, 2299], version = 2 } }

[forcing]

climate = {fields = ["acabf", "runoff", "tas"], short_hand = "SDBN1-1000m"}
ocean = {fields = ["TF"], short_hand = "none"}
