ismip7_to_pism = {"acabf" = "climatic_mass_balance", "dacabfdz" = "climatic_mass_balance_gradient", "mrro" = "runoff_rate", "dmrrodz" = "runoff_rate_gradient", "ts" = "ice_surface_temp", "dtsdz" = "ice_surface_temp_gradient", "tf" = "theta_ocean", "so" = "salinity_ocean", "geothermal_heat_flux1" = "bheatflx"}
version = "v2"
bucket = "pism-cloud-data"
prefix = "ismip7/greenland/input"
ice_sheet = "GrIS"

[domain]

crs = "EPSG:3413"
x_bounds = [-750650.0, 977350.0]
y_bounds = [-3412550.0, -604550.0]
resolution = "600m"

[gcms]

'CESM2-WACCM' = {ssp126 = {"historical" = [1978, 2015], "projection" = [2015, 2300], version = 2 }, ssp370 = {"historical" = [1978, 2015], "projection" = [2015, 2100], version = 2 }, ssp585 = {"historical" = [1978, 2015], "projection" = [2015, 2300], version = 2 } }

[forcing]

climate = {fields = ["acabf", "dacabfdz", "mrro", "ts", "dmrrodz", "dtsdz"], short_hand = "SDBN1-1000m"}
ocean = {fields = ["tf", "so"], short_hand = "ocean"}
