ismip7_to_pism = {"acabf" = "climatic_mass_balance", "runoff" = "water_input_rate", "tas" = "ice_surface_temp", "TF" = "theta_ocean", "geothermal_heat_flux1" = "bheatflx"}
gcms = ["CESM1-WACCM-SC"]
version = "v1"
bucket = "pism-cloud-data"
prefix = "input"

[domain]

x_bounds = [-653000.0, 879700.0]
y_bounds = [-3384350.0, -632750.0]
resolution = "900m"

[forcing]

bucket = "pism-cloud-data"
prefix = "kitp_forcing"
present_day_forcings = ["pdSST-pdSIC", "pdSST-pdSICSIT", "pa-pdSIC-ext"]
future_forcings = ["futSST-pdSIC", "pdSST-futArcSIC", "pa-futArcSIC-ext"]

[pathway]

baseline = {"start_year" = 1990, "end_year" = 2019}
