ismip7_to_pism = {"acabf" = "climatic_mass_balance", "runoff" = "water_input_rate", "tas" = "ice_surface_temp", "TF" = "theta_ocean"}
gcms = ["CESM2-WACCM"]

[domain]

x_bounds = [-654500, 894500]
y_bounds = [-504500, -3515500]

[pathway]

historical = {"start_year" = 2014, "end_year" = 2015, version = 1}
ssp585 = {"start_year" = 2015, "end_year" = 2016, version = 1 }

[forcing]

climate = {fields = ["acabf", "runoff", "tas"], short_hand = "SDBN1"}
ocean = {fields = ["TF"], short_hand = "none"}
